### PR TITLE
update score summary display

### PR DESCRIPTION
**Pull request by achen2401**
https://www.pivotaltracker.com/story/show/184299752

Changes included:
- update display of score summary to include # answered, score meaning and score range
- define maximum score in questionnaire CQL files
- remove hard-coded score params, e.g. ticks, domains from chart config JS file
- update graph Y-axis to reflect maximum score
- display score denominator on score summary UI
- display icon of different color for score of moderate severity

Other change:
- remove questionnaire selector dropdown

Example UI:
Screen Shot 2023-02-01 at 2 57 06 PM

Screen Shot 2023-01-26 at 9 05 43 AM

### CODE REVIEW

**Comment by mcjustin** [comment]
Thanks @achen2401  - I think we do need a bit more design, per my comment at https://www.pivotaltracker.com/story/show/184299752/comments/235214654 just now.

**Comment by achen2401** [comment]
@mcjustin & @sierramatice  This PR is ready for you to review again when you have a moment.

**Comment by mcjustin** [comment]
@achen2401  in what situations would the second screenshot version by displayed instead of the first?

**Comment by achen2401** [comment]
@mcjustin The second screenshot illustrates multi-level flagging (e.g. gad7 moderate severity)  - the icon has different color as per mockup from Sie-ce here:  https://docs.google.com/document/d/18ErTHgtb5tZ_cLvbcxCzWVLsEy3BZIljomzz6BEOEfY/edit#heading=h.xqlcl4534uhg

**Comment by sierramatice** [comment]
@achen2401 are we able to change the secondary alert's shape to this one from the icon library? https://mui.com/material-ui/material-icons/?query=alert&selected=ReportProblem I want to insure the difference is legible in b&w and for colorblindness

**Comment by mcjustin** [comment]
@sierramatice  can you please test this at https://femr.dcw.dev.cirg.uw.edu ? 
After Amy changes that icon, we'll need to update it again..

**Comment by achen2401** [comment]
thanks @sierramatice  I have changed the icon (see screenshot):
Screen Shot 2023-01-27 at 12 24 37 PM
@mcjustin FYI

**Review by mcjustin — APPROVED** [review]
I intended to approve this sooner @achen2401  since it's been on dev I've been hitting it a bit. Thanks!

**Pull request merged**
